### ISSUE TITLE
predict function with dataframe error?

### ISSUE THREAD

**Issue by francisvolh** [jamesepaterson/markrecaptureworkshop#2]
Hi James, 
I was trying your workshop and bumped into a problem with the predict function as you have written it, but at the same time found the solution you gave to someone else before. 

So on lines  426 and on you use predict() with the real data, but I kept getting the following error with the code as it was:
```
> dipper.js.predicted <- predict(dipper.js.models[[1]], newdata= newdipper, se = TRUE)
Error in rep(1, nocc + model.list$num) : invalid 'times' argument 
```
I tried you suggestion to another issue already closed, but for the new data:
`reals <- predict(dipper.js.models[[1]], newdata = data.frame(sex = dipper[c(1,23),2]),  se = TRUE)
`
replacing cjs with js, and it still does not work. 

In newdipper, sex is a factor. and it looks exactly the same as  data.frame(sex = dipper[c(1,23),2]) so I dont really understand what is going on here. 

Maybe its one of those updates within the data management packages the function calls? Anyway, any input would be nice if you come up with something! Thanks in advance for your awesome work and support to the community with such an excellent free workshop!!
Francis

**Comment by jamesepaterson** [comment]
Thanks Francis for pointing this out. 

This appears to be driven by a change in how predict.crm() works, with the preference to use the design data matrix for parameter predictions. The previous issue was for CJS prediction and the default for assigning character strings as factors when creating dataframes. This error you point out seems to be from a change in the way the functions work. 

See help predict.crm() for more details.

To update the workshop code to return the same results, I have updated the prediction lines (L426-L437) to use the ddl  (`dipper.js.ddl`) object, instead of `newdipper`. That resolves the issue for me (all predictions work without error) and allows me to complete the manual calculations below and predict population size at each capture event.

cheers!

**Comment by francisvolh** [comment]
Awesome James!! Thanks for the fix! Glad I could help somehow!
